# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IDSFoundation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IDSFoundation
  pod 'AFNetworking', '~> 3.0'

  target 'IDSFoundationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IDSFoundationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
